Pastebin/urls.py
from rest_framework.authtoken import views as auth_views
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
               path('admin/', admin.site.urls),
               path('api/', include(('api.urls', 'api'), namespace='api')),
               path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
               path('api-token-auth/', auth_views.obtain_auth_token),
               path('', include(('app.urls', 'app'), namespace='app')),
               ]

api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'snippet', views.SnippetViewSet)
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('', include(router.urls), name='api-root'),
]

app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import SnippetListView, SnippetDetailView, SnippetUpdateView, SnippetDeleteView, ProfileListView, SnippetCreateView

urlpatterns = [
        path('', SnippetListView.as_view(), name='snippet-list'),
        path('<str:pk>', SnippetDetailView.as_view(), name='snippet-detail'),
        
        path('new/', SnippetCreateView.as_view(), name='snippet-create'),
        path('<str:pk>/update/', SnippetUpdateView.as_view(), name='snippet-update'),
        path('<str:pk>/delete/', SnippetDeleteView.as_view(), name='snippet-delete'),

        path('register/', views.register, name='register'),
        path('profile/', ProfileListView.as_view(), name='profile-list'),
        path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(template_name='app/logout.html'), name='logout'),
        
        path('health/', views.health, name='health'),
        path('statistics/', views.statistics, name='statistics'),
               ]

api/models.py
from django.db import models

# Create your models here.

app/models.py
from .helpers import url_shortner
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

class CustomUser(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.username

class Snippet(models.Model):
    id = models.CharField(primary_key=True, max_length=19, default=url_shortner, editable=False)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, default="Untitled")
    content = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    expiration_date = models.DateTimeField(null=True, blank=True)
    exposure_status = models.BooleanField()
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('app:snippet-detail', kwargs={'pk': self.pk})

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

api/views.py
from api.serializers import SnippetSerializer, UserSerializer, GroupSerializer
from django.contrib.auth.models import Group
from rest_framework import viewsets, permissions
from app.models import Snippet, CustomUser


class SnippetViewSet(viewsets.ModelViewSet):
    queryset = Snippet.objects.all()
    serializer_class = SnippetSerializer


class UserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

app/views.py
import csv
from django.http import HttpResponse
from app.models import Snippet, CustomUser
from app.helpers import get_pastes_num
from django.contrib import messages
from django.http import JsonResponse
from app.forms import UserRegistrationForm
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class ProfileListView(LoginRequiredMixin, ListView):
    queryset = Snippet.objects.all().order_by('-creation_date')
    template_name = 'app/profile_list.html'
    context_object_name = 'snippets'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_snippets'] = Snippet.objects.all().filter(owner=self.request.user.id)
        return context

class SnippetListView(ListView):
    model = Snippet
    context_object_name = 'snippets'
    ordering = ['-creation_date']


class SnippetDetailView(DetailView):
    model = Snippet
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['snippets'] = Snippet.objects.all().order_by('-creation_date')
        return context

class SnippetCreateView(LoginRequiredMixin, CreateView):
    model = Snippet
    fields = ['title', 'content', 'expiration_date', 'exposure_status']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class SnippetUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Snippet
    fields = ['title', 'content', 'expiration_date', 'exposure_status']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        Snippet = self.get_object()
        if self.request.user == Snippet.owner:
            return True
        return False

class SnippetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Snippet
    success_url = '/'

    def test_func(self):
        Snippet = self.get_object()
        if self.request.user == Snippet.owner:
            return True
        return False

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created ')
            return redirect('app:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'app/register.html', {'form': form})

def health(request):
    state = {"status": "UP"}
    return JsonResponse(state)

def statistics(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="statistics.csv"'
    writer = csv.writer(response)

    writer.writerow(['username', 'snippets_number'])
    writer.writerows(get_pastes_num())
    return response

    

   

app/templates/app/base.html
 {% load static %}
 <!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    {% if title %}
        <title>Pastebin - {{ title }}</title>
    {% else %}
        <title>Pastebin</title>
    {% endif %}

    <link rel="icon" href="{% static 'images/favicon.ico' %}"/> 
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon-96x96.png' %}">
    
    <link rel="manifest" href="{% static 'js/manifest.json' %}">
    <meta name="theme-color" content="#ffffff">

</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'app:snippet-list' %}">Pastebin</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'app:snippet-list' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'api:api-root' %}">API</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'app:snippet-create' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'app:profile-list' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'app:logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'app:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'app:register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Latest snippets</h3>
            <p class='text-muted'>Here is the latest snippets from users
              <ul class="list-group">

                {% for snippet in snippets %}
                  <li class="list-group-item list-group-item-secondary">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><a href="{% url 'app:snippet-detail' pk=snippet.id %}">{{ snippet.title }}</a></h5>
                    <small>{{ snippet.creation_date|date:"d/n/y, g:iA" }}</small>
                    <a class="mr-2" href="{% url 'app:profile-list' %}">{{ snippet.owner }}</a>
                  </li>
                {% endfor %}

              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

app/templates/app/index.html
{% extends "app/base.html" %}
{% block content %}

{% endblock content %}

app/templates/app/login.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'app:register' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock content %}

app/templates/app/logout.html
{% extends "app/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <a class="text-muted" href="{% url 'app:login' %}">Log In</a>
    </div>
{% endblock content %}

app/templates/app/profile.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        {% comment %} <img class="rounded-circle account-img" src="{{ user.profile.image.url }}"> {% endcomment %}
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <ul class="list-group">
                {% for snippet in all_snippets %}
                    <li class="list-group-item list-group-item-secondary">
                    <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><a href="{% url 'app:detail' pk=snippet.id %}">{{ snippet.title }}</a></h5>
                    <small>{{ snippet.creation_date|date:"d/n/y, g:iA" }}</small>
                    <a class="mr-2" href="#">{{ snippet.owner }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

app/templates/app/profile_list.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <ul class="list-group">
                {% for snippet in user_snippets %}
                    <li class="list-group-item list-group-item-secondary">
                      <div class="d-flex w-100 justify-content-between">
                      <h5 class="mb-1"><a href="{% url 'app:snippet-detail' pk=snippet.id %}">{{ snippet.title }}</a></h5>
                      <small>{{ snippet.creation_date|date:"d/n/y, g:iA" }}</small>
                      <a class="mr-2" href="#">{{ snippet.owner }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

app/templates/app/register.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="#">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}

app/templates/app/snippet_confirm_delete.html
{% extends "app/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Snippet</legend>
                <h2>Are you sure you want to delete the snippet "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'app:snippet-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/app/snippet_detail.html
{% extends "app/base.html" %}
{% block content %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="#">{{ object.owner }}</a>
          <small class="text-muted">{{ object.creation_date|date:"d/n/y, g:iA" }}</small>
          {% if object.owner == user %}
            <div>
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'app:snippet-update' object.id %}">Update</a>
              <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'app:snippet-delete' object.id %}">Delete</a>
            </div>
          {% endif %}
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.content }}</p>
      </div>
    </article>
{% endblock content %}

app/templates/app/snippet_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <input class="btn btn-outline-info" type="submit" value="Post">
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/app/snippet_list.html
{% extends "app/base.html" %}
{% block content %}

{% endblock content %}